<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_NameEmailGenderMaleFemaleOtherMobile(1_53b2a4</name>
   <tag></tag>
   <elementGuidId>087291c9-2411-4d89-b768-6df9c29f75bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>966c068f-6860-4f99-9159-6ed6f6f9019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>28ef783f-2e14-4825-a76b-97244daab217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjectsMaths HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CityHaryana   option Karnal focused, 1 of 2. 2 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select CityKarnalPanipatSubmit</value>
      <webElementGuid>a7d9ba1b-6a68-4395-9a4c-a0435eb7d9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>5984786f-f25e-447e-944c-38e79440cb6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>2f4063d8-fa0e-434a-9ebd-46980c3a33ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/form</value>
      <webElementGuid>6fbc40ba-0a88-4b50-a6ec-1da32b54fd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Registration Form'])[1]/following::form[1]</value>
      <webElementGuid>975e6baf-d8c4-41dc-8358-ff6717e5808b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::form[1]</value>
      <webElementGuid>34a52600-6465-40f8-9715-ca1eb39be2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>25e7230f-d165-45bb-bf4e-d3d00d87c3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjectsMaths HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CityHaryana   option Karnal focused, 1 of 2. 2 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select CityKarnalPanipatSubmit' or . = 'NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjectsMaths HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CityHaryana   option Karnal focused, 1 of 2. 2 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select CityKarnalPanipatSubmit')]</value>
      <webElementGuid>f6e2198c-5760-4a1f-8f7e-3bbb06bbd177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
